version: '3.7'
services: 
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'pos-img'
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
  # db:
  #   image: mysql:5.7
  #   restart: always
  #   ports: 
  #     - "3306:3306"
  #   environment:
  #     MYSQL_DATABASE: 'q1'
  #     MYSQL_ALLOW_EMPTY_PASSWORD: 1
  #     MYSQL_ROOT_PASSWORD: ""
  #   volumes:
  #     - ./db:/var/lib/mysql
  #   command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
